# Generated by Django 6.0.2 on 2026-02-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_document_pages_processed_document_total_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('parsing', 'Parsing'), ('awaiting_analysis', 'Ready'), ('processing', 'Processing AI'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
