# Generated by Django 6.0.2 on 2026-02-23 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_document_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='checks_remaining',
            field=models.IntegerField(default=2),
        ),
    ]
