# Generated by Django 6.0.2 on 2026-02-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_documentpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentpage',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
