# Generated by Django 6.0.2 on 2026-03-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_documentpage_extracted_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/'),
        ),
    ]
