# Generated by Django 6.0.2 on 2026-02-23 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='pages_processed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='total_pages',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
