# Generated by Django 6.0.2 on 2026-02-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_userprofile_checks_remaining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='subscription_tier',
            field=models.CharField(choices=[('free', 'Free'), ('single', 'Single'), ('pro', 'PRO'), ('business', 'Business')], default='free', max_length=20),
        ),
    ]
